# Site settings
title: Zhiyuan Cheng`s Personal Site # site title
description: >- # site description
  Personal notes on SLAM, VLA, and related engineering work.
lang: en-US # default lang
timezone: Asia/Shanghai # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/ZYCheng1002/ZYCheng1002.github.io # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Zhiyuan Cheng # author name
  bio: >- # tell to the world
    Algorithm Engineer working on SLAM, VLA, and practical spatial intelligence systems. Notes, code, and experiments <a href="https://github.com/ZYCheng1002" target="_blank" rel="noopener">@github</a>.
  username: Zhiyuan Cheng # general username
  github: ZYCheng1002 # github username
  twitter: twitter_username # twitter username
  facebook: facebook_username # facebook username
  email: cczyy0@gmail.com # email adress
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url:  #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Homepage limit posts
number_of_posts: 5

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - klise-*.gem

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
